import { GoogleGenAI } from "@google/genai";

// Initialize Gemini Client
// CRITICAL: We use process.env.API_KEY directly as per guidelines.
export const editImageWithAI = async (
  base64Image: string,
  prompt: string
): Promise<string> => {
  // Check for API Key at runtime
  // Check for API Key at runtime (Support both VITE_ prefix and plain for different envs)
  const apiKey = (import.meta.env.VITE_GEMINI_API_KEY || (import.meta as any).env?.GEMINI_API_KEY || process.env.API_KEY) as string;

  if (!apiKey) {
    throw new Error("API Key is missing. Please set GEMINI_API_KEY in your deployment settings.");
  }

  // Initialize client lazily
  const ai = new GoogleGenAI({ apiKey });

  try {
    // Remove data URL prefix if present (e.g., "data:image/png;base64,")
    const base64Data = base64Image.split(',')[1] || base64Image;
    const mimeType = base64Image.substring(base64Image.indexOf(':') + 1, base64Image.indexOf(';')) || 'image/png';

    const model = 'gemini-2.5-flash-image';

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          {
            text: `${prompt}. Return ONLY the image. Maintain the core structure of the original image unless specified otherwise.`,
          },
        ],
      },
    });

    // Iterate to find the image part
    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          const returnMime = part.inlineData.mimeType || 'image/png';
          return `data:${returnMime};base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by Gemini.");

  } catch (error) {
    console.error("Gemini Image Edit Error:", error);
    throw error;
  }
};
