import { GoogleGenAI } from "@google/genai";

// Initialize Gemini Client
// CRITICAL: We use process.env.API_KEY directly as per guidelines.
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Uses Gemini to "edit" or transform an image based on a prompt.
 * Uses gemini-2.5-flash-image for balanced speed and creativity in editing.
 */
export const editImageWithAI = async (
  base64Image: string,
  prompt: string
): Promise<string> => {
  try {
    // Remove data URL prefix if present (e.g., "data:image/png;base64,")
    const base64Data = base64Image.split(',')[1] || base64Image;
    const mimeType = base64Image.substring(base64Image.indexOf(':') + 1, base64Image.indexOf(';')) || 'image/png';

    const model = 'gemini-2.5-flash-image';

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType, 
            },
          },
          {
            text: `${prompt}. Return ONLY the image. Maintain the core structure of the original image unless specified otherwise.`,
          },
        ],
      },
      // Using tools or config if needed, but for direct image-to-image/text-to-image via generateContent,
      // we rely on the model returning an inlineData part.
    });

    // Iterate to find the image part
    if (response.candidates && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                const returnMime = part.inlineData.mimeType || 'image/png';
                return `data:${returnMime};base64,${part.inlineData.data}`;
            }
        }
    }
    
    throw new Error("No image generated by Gemini.");

  } catch (error) {
    console.error("Gemini Image Edit Error:", error);
    throw error;
  }
};
